# Generated by Django 3.1.5 on 2021-01-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(help_text='Bitcoin public key', max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', help_text='Descriptive text to associate with the public key.', max_length=100)),
            ],
        ),
    ]
